/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.startarget.portlet.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.startarget.portlet.model.AccountItem;
import com.startarget.portlet.model.AccountItemModel;
import com.startarget.portlet.model.AccountItemSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the AccountItem service. Represents a row in the &quot;lims_AccountItem&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.startarget.portlet.model.AccountItemModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AccountItemImpl}.
 * </p>
 *
 * @author chaojie
 * @see AccountItemImpl
 * @see com.startarget.portlet.model.AccountItem
 * @see com.startarget.portlet.model.AccountItemModel
 * @generated
 */
@JSON(strict = true)
public class AccountItemModelImpl extends BaseModelImpl<AccountItem>
	implements AccountItemModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a account item model instance should use the {@link com.startarget.portlet.model.AccountItem} interface instead.
	 */
	public static final String TABLE_NAME = "lims_AccountItem";
	public static final Object[][] TABLE_COLUMNS = {
			{ "accountItemId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "name", Types.VARCHAR },
			{ "parentName", Types.VARCHAR },
			{ "itemCode", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table lims_AccountItem (accountItemId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,name VARCHAR(75) null,parentName VARCHAR(75) null,itemCode LONG)";
	public static final String TABLE_SQL_DROP = "drop table lims_AccountItem";
	public static final String ORDER_BY_JPQL = " ORDER BY accountItem.accountItemId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY lims_AccountItem.accountItemId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.startarget.portlet.model.AccountItem"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.startarget.portlet.model.AccountItem"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static AccountItem toModel(AccountItemSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		AccountItem model = new AccountItemImpl();

		model.setAccountItemId(soapModel.getAccountItemId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setName(soapModel.getName());
		model.setParentName(soapModel.getParentName());
		model.setItemCode(soapModel.getItemCode());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<AccountItem> toModels(AccountItemSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<AccountItem> models = new ArrayList<AccountItem>(soapModels.length);

		for (AccountItemSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.startarget.portlet.model.AccountItem"));

	public AccountItemModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _accountItemId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAccountItemId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _accountItemId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return AccountItem.class;
	}

	@Override
	public String getModelClassName() {
		return AccountItem.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("accountItemId", getAccountItemId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("name", getName());
		attributes.put("parentName", getParentName());
		attributes.put("itemCode", getItemCode());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long accountItemId = (Long)attributes.get("accountItemId");

		if (accountItemId != null) {
			setAccountItemId(accountItemId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}

		String parentName = (String)attributes.get("parentName");

		if (parentName != null) {
			setParentName(parentName);
		}

		Long itemCode = (Long)attributes.get("itemCode");

		if (itemCode != null) {
			setItemCode(itemCode);
		}
	}

	@JSON
	@Override
	public long getAccountItemId() {
		return _accountItemId;
	}

	@Override
	public void setAccountItemId(long accountItemId) {
		_accountItemId = accountItemId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@JSON
	@Override
	public String getParentName() {
		if (_parentName == null) {
			return StringPool.BLANK;
		}
		else {
			return _parentName;
		}
	}

	@Override
	public void setParentName(String parentName) {
		_parentName = parentName;
	}

	@JSON
	@Override
	public long getItemCode() {
		return _itemCode;
	}

	@Override
	public void setItemCode(long itemCode) {
		_itemCode = itemCode;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			AccountItem.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public AccountItem toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (AccountItem)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AccountItemImpl accountItemImpl = new AccountItemImpl();

		accountItemImpl.setAccountItemId(getAccountItemId());
		accountItemImpl.setGroupId(getGroupId());
		accountItemImpl.setCompanyId(getCompanyId());
		accountItemImpl.setUserId(getUserId());
		accountItemImpl.setUserName(getUserName());
		accountItemImpl.setCreateDate(getCreateDate());
		accountItemImpl.setModifiedDate(getModifiedDate());
		accountItemImpl.setName(getName());
		accountItemImpl.setParentName(getParentName());
		accountItemImpl.setItemCode(getItemCode());

		accountItemImpl.resetOriginalValues();

		return accountItemImpl;
	}

	@Override
	public int compareTo(AccountItem accountItem) {
		long primaryKey = accountItem.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof AccountItem)) {
			return false;
		}

		AccountItem accountItem = (AccountItem)obj;

		long primaryKey = accountItem.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<AccountItem> toCacheModel() {
		AccountItemCacheModel accountItemCacheModel = new AccountItemCacheModel();

		accountItemCacheModel.accountItemId = getAccountItemId();

		accountItemCacheModel.groupId = getGroupId();

		accountItemCacheModel.companyId = getCompanyId();

		accountItemCacheModel.userId = getUserId();

		accountItemCacheModel.userName = getUserName();

		String userName = accountItemCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			accountItemCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			accountItemCacheModel.createDate = createDate.getTime();
		}
		else {
			accountItemCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			accountItemCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			accountItemCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		accountItemCacheModel.name = getName();

		String name = accountItemCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			accountItemCacheModel.name = null;
		}

		accountItemCacheModel.parentName = getParentName();

		String parentName = accountItemCacheModel.parentName;

		if ((parentName != null) && (parentName.length() == 0)) {
			accountItemCacheModel.parentName = null;
		}

		accountItemCacheModel.itemCode = getItemCode();

		return accountItemCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(21);

		sb.append("{accountItemId=");
		sb.append(getAccountItemId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", parentName=");
		sb.append(getParentName());
		sb.append(", itemCode=");
		sb.append(getItemCode());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(34);

		sb.append("<model><model-name>");
		sb.append("com.startarget.portlet.model.AccountItem");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>accountItemId</column-name><column-value><![CDATA[");
		sb.append(getAccountItemId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>parentName</column-name><column-value><![CDATA[");
		sb.append(getParentName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>itemCode</column-name><column-value><![CDATA[");
		sb.append(getItemCode());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = AccountItem.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			AccountItem.class
		};
	private long _accountItemId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private String _name;
	private String _parentName;
	private long _itemCode;
	private AccountItem _escapedModel;
}