/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.startarget.portlet.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.startarget.portlet.model.BudgetItem;
import com.startarget.portlet.model.BudgetItemModel;
import com.startarget.portlet.model.BudgetItemSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the BudgetItem service. Represents a row in the &quot;lims_BudgetItem&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.startarget.portlet.model.BudgetItemModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BudgetItemImpl}.
 * </p>
 *
 * @author chaojie
 * @see BudgetItemImpl
 * @see com.startarget.portlet.model.BudgetItem
 * @see com.startarget.portlet.model.BudgetItemModel
 * @generated
 */
@JSON(strict = true)
public class BudgetItemModelImpl extends BaseModelImpl<BudgetItem>
	implements BudgetItemModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a budget item model instance should use the {@link com.startarget.portlet.model.BudgetItem} interface instead.
	 */
	public static final String TABLE_NAME = "lims_BudgetItem";
	public static final Object[][] TABLE_COLUMNS = {
			{ "budgetItemId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "budgetId", Types.BIGINT },
			{ "accountItemId", Types.BIGINT },
			{ "accountItemName", Types.VARCHAR },
			{ "itemCode", Types.BIGINT },
			{ "budgetTotal", Types.DOUBLE },
			{ "budgetUsed", Types.DOUBLE }
		};
	public static final String TABLE_SQL_CREATE = "create table lims_BudgetItem (budgetItemId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,budgetId LONG,accountItemId LONG,accountItemName VARCHAR(75) null,itemCode LONG,budgetTotal DOUBLE,budgetUsed DOUBLE)";
	public static final String TABLE_SQL_DROP = "drop table lims_BudgetItem";
	public static final String ORDER_BY_JPQL = " ORDER BY budgetItem.budgetItemId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY lims_BudgetItem.budgetItemId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.startarget.portlet.model.BudgetItem"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.startarget.portlet.model.BudgetItem"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static BudgetItem toModel(BudgetItemSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		BudgetItem model = new BudgetItemImpl();

		model.setBudgetItemId(soapModel.getBudgetItemId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setBudgetId(soapModel.getBudgetId());
		model.setAccountItemId(soapModel.getAccountItemId());
		model.setAccountItemName(soapModel.getAccountItemName());
		model.setItemCode(soapModel.getItemCode());
		model.setBudgetTotal(soapModel.getBudgetTotal());
		model.setBudgetUsed(soapModel.getBudgetUsed());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<BudgetItem> toModels(BudgetItemSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<BudgetItem> models = new ArrayList<BudgetItem>(soapModels.length);

		for (BudgetItemSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.startarget.portlet.model.BudgetItem"));

	public BudgetItemModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _budgetItemId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setBudgetItemId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _budgetItemId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return BudgetItem.class;
	}

	@Override
	public String getModelClassName() {
		return BudgetItem.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("budgetItemId", getBudgetItemId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("budgetId", getBudgetId());
		attributes.put("accountItemId", getAccountItemId());
		attributes.put("accountItemName", getAccountItemName());
		attributes.put("itemCode", getItemCode());
		attributes.put("budgetTotal", getBudgetTotal());
		attributes.put("budgetUsed", getBudgetUsed());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long budgetItemId = (Long)attributes.get("budgetItemId");

		if (budgetItemId != null) {
			setBudgetItemId(budgetItemId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long budgetId = (Long)attributes.get("budgetId");

		if (budgetId != null) {
			setBudgetId(budgetId);
		}

		Long accountItemId = (Long)attributes.get("accountItemId");

		if (accountItemId != null) {
			setAccountItemId(accountItemId);
		}

		String accountItemName = (String)attributes.get("accountItemName");

		if (accountItemName != null) {
			setAccountItemName(accountItemName);
		}

		Long itemCode = (Long)attributes.get("itemCode");

		if (itemCode != null) {
			setItemCode(itemCode);
		}

		Double budgetTotal = (Double)attributes.get("budgetTotal");

		if (budgetTotal != null) {
			setBudgetTotal(budgetTotal);
		}

		Double budgetUsed = (Double)attributes.get("budgetUsed");

		if (budgetUsed != null) {
			setBudgetUsed(budgetUsed);
		}
	}

	@JSON
	@Override
	public long getBudgetItemId() {
		return _budgetItemId;
	}

	@Override
	public void setBudgetItemId(long budgetItemId) {
		_budgetItemId = budgetItemId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getBudgetId() {
		return _budgetId;
	}

	@Override
	public void setBudgetId(long budgetId) {
		_budgetId = budgetId;
	}

	@JSON
	@Override
	public long getAccountItemId() {
		return _accountItemId;
	}

	@Override
	public void setAccountItemId(long accountItemId) {
		_accountItemId = accountItemId;
	}

	@JSON
	@Override
	public String getAccountItemName() {
		if (_accountItemName == null) {
			return StringPool.BLANK;
		}
		else {
			return _accountItemName;
		}
	}

	@Override
	public void setAccountItemName(String accountItemName) {
		_accountItemName = accountItemName;
	}

	@JSON
	@Override
	public long getItemCode() {
		return _itemCode;
	}

	@Override
	public void setItemCode(long itemCode) {
		_itemCode = itemCode;
	}

	@JSON
	@Override
	public double getBudgetTotal() {
		return _budgetTotal;
	}

	@Override
	public void setBudgetTotal(double budgetTotal) {
		_budgetTotal = budgetTotal;
	}

	@JSON
	@Override
	public double getBudgetUsed() {
		return _budgetUsed;
	}

	@Override
	public void setBudgetUsed(double budgetUsed) {
		_budgetUsed = budgetUsed;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			BudgetItem.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public BudgetItem toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (BudgetItem)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		BudgetItemImpl budgetItemImpl = new BudgetItemImpl();

		budgetItemImpl.setBudgetItemId(getBudgetItemId());
		budgetItemImpl.setGroupId(getGroupId());
		budgetItemImpl.setCompanyId(getCompanyId());
		budgetItemImpl.setUserId(getUserId());
		budgetItemImpl.setUserName(getUserName());
		budgetItemImpl.setCreateDate(getCreateDate());
		budgetItemImpl.setModifiedDate(getModifiedDate());
		budgetItemImpl.setBudgetId(getBudgetId());
		budgetItemImpl.setAccountItemId(getAccountItemId());
		budgetItemImpl.setAccountItemName(getAccountItemName());
		budgetItemImpl.setItemCode(getItemCode());
		budgetItemImpl.setBudgetTotal(getBudgetTotal());
		budgetItemImpl.setBudgetUsed(getBudgetUsed());

		budgetItemImpl.resetOriginalValues();

		return budgetItemImpl;
	}

	@Override
	public int compareTo(BudgetItem budgetItem) {
		long primaryKey = budgetItem.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof BudgetItem)) {
			return false;
		}

		BudgetItem budgetItem = (BudgetItem)obj;

		long primaryKey = budgetItem.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<BudgetItem> toCacheModel() {
		BudgetItemCacheModel budgetItemCacheModel = new BudgetItemCacheModel();

		budgetItemCacheModel.budgetItemId = getBudgetItemId();

		budgetItemCacheModel.groupId = getGroupId();

		budgetItemCacheModel.companyId = getCompanyId();

		budgetItemCacheModel.userId = getUserId();

		budgetItemCacheModel.userName = getUserName();

		String userName = budgetItemCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			budgetItemCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			budgetItemCacheModel.createDate = createDate.getTime();
		}
		else {
			budgetItemCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			budgetItemCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			budgetItemCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		budgetItemCacheModel.budgetId = getBudgetId();

		budgetItemCacheModel.accountItemId = getAccountItemId();

		budgetItemCacheModel.accountItemName = getAccountItemName();

		String accountItemName = budgetItemCacheModel.accountItemName;

		if ((accountItemName != null) && (accountItemName.length() == 0)) {
			budgetItemCacheModel.accountItemName = null;
		}

		budgetItemCacheModel.itemCode = getItemCode();

		budgetItemCacheModel.budgetTotal = getBudgetTotal();

		budgetItemCacheModel.budgetUsed = getBudgetUsed();

		return budgetItemCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(27);

		sb.append("{budgetItemId=");
		sb.append(getBudgetItemId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", budgetId=");
		sb.append(getBudgetId());
		sb.append(", accountItemId=");
		sb.append(getAccountItemId());
		sb.append(", accountItemName=");
		sb.append(getAccountItemName());
		sb.append(", itemCode=");
		sb.append(getItemCode());
		sb.append(", budgetTotal=");
		sb.append(getBudgetTotal());
		sb.append(", budgetUsed=");
		sb.append(getBudgetUsed());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(43);

		sb.append("<model><model-name>");
		sb.append("com.startarget.portlet.model.BudgetItem");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>budgetItemId</column-name><column-value><![CDATA[");
		sb.append(getBudgetItemId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>budgetId</column-name><column-value><![CDATA[");
		sb.append(getBudgetId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>accountItemId</column-name><column-value><![CDATA[");
		sb.append(getAccountItemId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>accountItemName</column-name><column-value><![CDATA[");
		sb.append(getAccountItemName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>itemCode</column-name><column-value><![CDATA[");
		sb.append(getItemCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>budgetTotal</column-name><column-value><![CDATA[");
		sb.append(getBudgetTotal());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>budgetUsed</column-name><column-value><![CDATA[");
		sb.append(getBudgetUsed());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = BudgetItem.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			BudgetItem.class
		};
	private long _budgetItemId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private long _budgetId;
	private long _accountItemId;
	private String _accountItemName;
	private long _itemCode;
	private double _budgetTotal;
	private double _budgetUsed;
	private BudgetItem _escapedModel;
}