/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.startarget.portlet.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the AccountItem service. Represents a row in the &quot;lims_AccountItem&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.startarget.portlet.model.impl.AccountItemModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.startarget.portlet.model.impl.AccountItemImpl}.
 * </p>
 *
 * @author chaojie
 * @see AccountItem
 * @see com.startarget.portlet.model.impl.AccountItemImpl
 * @see com.startarget.portlet.model.impl.AccountItemModelImpl
 * @generated
 */
public interface AccountItemModel extends BaseModel<AccountItem>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a account item model instance should use the {@link AccountItem} interface instead.
	 */

	/**
	 * Returns the primary key of this account item.
	 *
	 * @return the primary key of this account item
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this account item.
	 *
	 * @param primaryKey the primary key of this account item
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the account item ID of this account item.
	 *
	 * @return the account item ID of this account item
	 */
	public long getAccountItemId();

	/**
	 * Sets the account item ID of this account item.
	 *
	 * @param accountItemId the account item ID of this account item
	 */
	public void setAccountItemId(long accountItemId);

	/**
	 * Returns the group ID of this account item.
	 *
	 * @return the group ID of this account item
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this account item.
	 *
	 * @param groupId the group ID of this account item
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this account item.
	 *
	 * @return the company ID of this account item
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this account item.
	 *
	 * @param companyId the company ID of this account item
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this account item.
	 *
	 * @return the user ID of this account item
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this account item.
	 *
	 * @param userId the user ID of this account item
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this account item.
	 *
	 * @return the user uuid of this account item
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this account item.
	 *
	 * @param userUuid the user uuid of this account item
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this account item.
	 *
	 * @return the user name of this account item
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this account item.
	 *
	 * @param userName the user name of this account item
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this account item.
	 *
	 * @return the create date of this account item
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this account item.
	 *
	 * @param createDate the create date of this account item
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this account item.
	 *
	 * @return the modified date of this account item
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this account item.
	 *
	 * @param modifiedDate the modified date of this account item
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this account item.
	 *
	 * @return the name of this account item
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this account item.
	 *
	 * @param name the name of this account item
	 */
	public void setName(String name);

	/**
	 * Returns the parent name of this account item.
	 *
	 * @return the parent name of this account item
	 */
	@AutoEscape
	public String getParentName();

	/**
	 * Sets the parent name of this account item.
	 *
	 * @param parentName the parent name of this account item
	 */
	public void setParentName(String parentName);

	/**
	 * Returns the item code of this account item.
	 *
	 * @return the item code of this account item
	 */
	public long getItemCode();

	/**
	 * Sets the item code of this account item.
	 *
	 * @param itemCode the item code of this account item
	 */
	public void setItemCode(long itemCode);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.startarget.portlet.model.AccountItem accountItem);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.startarget.portlet.model.AccountItem> toCacheModel();

	@Override
	public com.startarget.portlet.model.AccountItem toEscapedModel();

	@Override
	public com.startarget.portlet.model.AccountItem toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}