/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.startarget.portlet.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the BudgetItem service. Represents a row in the &quot;lims_BudgetItem&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.startarget.portlet.model.impl.BudgetItemModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.startarget.portlet.model.impl.BudgetItemImpl}.
 * </p>
 *
 * @author chaojie
 * @see BudgetItem
 * @see com.startarget.portlet.model.impl.BudgetItemImpl
 * @see com.startarget.portlet.model.impl.BudgetItemModelImpl
 * @generated
 */
public interface BudgetItemModel extends BaseModel<BudgetItem>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a budget item model instance should use the {@link BudgetItem} interface instead.
	 */

	/**
	 * Returns the primary key of this budget item.
	 *
	 * @return the primary key of this budget item
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this budget item.
	 *
	 * @param primaryKey the primary key of this budget item
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the budget item ID of this budget item.
	 *
	 * @return the budget item ID of this budget item
	 */
	public long getBudgetItemId();

	/**
	 * Sets the budget item ID of this budget item.
	 *
	 * @param budgetItemId the budget item ID of this budget item
	 */
	public void setBudgetItemId(long budgetItemId);

	/**
	 * Returns the group ID of this budget item.
	 *
	 * @return the group ID of this budget item
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this budget item.
	 *
	 * @param groupId the group ID of this budget item
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this budget item.
	 *
	 * @return the company ID of this budget item
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this budget item.
	 *
	 * @param companyId the company ID of this budget item
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this budget item.
	 *
	 * @return the user ID of this budget item
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this budget item.
	 *
	 * @param userId the user ID of this budget item
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this budget item.
	 *
	 * @return the user uuid of this budget item
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this budget item.
	 *
	 * @param userUuid the user uuid of this budget item
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this budget item.
	 *
	 * @return the user name of this budget item
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this budget item.
	 *
	 * @param userName the user name of this budget item
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this budget item.
	 *
	 * @return the create date of this budget item
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this budget item.
	 *
	 * @param createDate the create date of this budget item
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this budget item.
	 *
	 * @return the modified date of this budget item
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this budget item.
	 *
	 * @param modifiedDate the modified date of this budget item
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the budget ID of this budget item.
	 *
	 * @return the budget ID of this budget item
	 */
	public long getBudgetId();

	/**
	 * Sets the budget ID of this budget item.
	 *
	 * @param budgetId the budget ID of this budget item
	 */
	public void setBudgetId(long budgetId);

	/**
	 * Returns the account item ID of this budget item.
	 *
	 * @return the account item ID of this budget item
	 */
	public long getAccountItemId();

	/**
	 * Sets the account item ID of this budget item.
	 *
	 * @param accountItemId the account item ID of this budget item
	 */
	public void setAccountItemId(long accountItemId);

	/**
	 * Returns the account item name of this budget item.
	 *
	 * @return the account item name of this budget item
	 */
	@AutoEscape
	public String getAccountItemName();

	/**
	 * Sets the account item name of this budget item.
	 *
	 * @param accountItemName the account item name of this budget item
	 */
	public void setAccountItemName(String accountItemName);

	/**
	 * Returns the item code of this budget item.
	 *
	 * @return the item code of this budget item
	 */
	public long getItemCode();

	/**
	 * Sets the item code of this budget item.
	 *
	 * @param itemCode the item code of this budget item
	 */
	public void setItemCode(long itemCode);

	/**
	 * Returns the budget total of this budget item.
	 *
	 * @return the budget total of this budget item
	 */
	public double getBudgetTotal();

	/**
	 * Sets the budget total of this budget item.
	 *
	 * @param budgetTotal the budget total of this budget item
	 */
	public void setBudgetTotal(double budgetTotal);

	/**
	 * Returns the budget used of this budget item.
	 *
	 * @return the budget used of this budget item
	 */
	public double getBudgetUsed();

	/**
	 * Sets the budget used of this budget item.
	 *
	 * @param budgetUsed the budget used of this budget item
	 */
	public void setBudgetUsed(double budgetUsed);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.startarget.portlet.model.BudgetItem budgetItem);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.startarget.portlet.model.BudgetItem> toCacheModel();

	@Override
	public com.startarget.portlet.model.BudgetItem toEscapedModel();

	@Override
	public com.startarget.portlet.model.BudgetItem toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}