/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.startarget.portlet.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the BudgetApplication service. Represents a row in the &quot;lims_BudgetApplication&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.startarget.portlet.model.impl.BudgetApplicationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.startarget.portlet.model.impl.BudgetApplicationImpl}.
 * </p>
 *
 * @author chaojie
 * @see BudgetApplication
 * @see com.startarget.portlet.model.impl.BudgetApplicationImpl
 * @see com.startarget.portlet.model.impl.BudgetApplicationModelImpl
 * @generated
 */
public interface BudgetApplicationModel extends BaseModel<BudgetApplication>,
	GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a budget application model instance should use the {@link BudgetApplication} interface instead.
	 */

	/**
	 * Returns the primary key of this budget application.
	 *
	 * @return the primary key of this budget application
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this budget application.
	 *
	 * @param primaryKey the primary key of this budget application
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the budget application ID of this budget application.
	 *
	 * @return the budget application ID of this budget application
	 */
	public long getBudgetApplicationId();

	/**
	 * Sets the budget application ID of this budget application.
	 *
	 * @param budgetApplicationId the budget application ID of this budget application
	 */
	public void setBudgetApplicationId(long budgetApplicationId);

	/**
	 * Returns the group ID of this budget application.
	 *
	 * @return the group ID of this budget application
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this budget application.
	 *
	 * @param groupId the group ID of this budget application
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this budget application.
	 *
	 * @return the company ID of this budget application
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this budget application.
	 *
	 * @param companyId the company ID of this budget application
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this budget application.
	 *
	 * @return the user ID of this budget application
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this budget application.
	 *
	 * @param userId the user ID of this budget application
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this budget application.
	 *
	 * @return the user uuid of this budget application
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this budget application.
	 *
	 * @param userUuid the user uuid of this budget application
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this budget application.
	 *
	 * @return the user name of this budget application
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this budget application.
	 *
	 * @param userName the user name of this budget application
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this budget application.
	 *
	 * @return the create date of this budget application
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this budget application.
	 *
	 * @param createDate the create date of this budget application
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this budget application.
	 *
	 * @return the modified date of this budget application
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this budget application.
	 *
	 * @param modifiedDate the modified date of this budget application
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the applicant ID of this budget application.
	 *
	 * @return the applicant ID of this budget application
	 */
	public long getApplicantId();

	/**
	 * Sets the applicant ID of this budget application.
	 *
	 * @param applicantId the applicant ID of this budget application
	 */
	public void setApplicantId(long applicantId);

	/**
	 * Returns the applicant name of this budget application.
	 *
	 * @return the applicant name of this budget application
	 */
	@AutoEscape
	public String getApplicantName();

	/**
	 * Sets the applicant name of this budget application.
	 *
	 * @param applicantName the applicant name of this budget application
	 */
	public void setApplicantName(String applicantName);

	/**
	 * Returns the auditor ID of this budget application.
	 *
	 * @return the auditor ID of this budget application
	 */
	public long getAuditorId();

	/**
	 * Sets the auditor ID of this budget application.
	 *
	 * @param auditorId the auditor ID of this budget application
	 */
	public void setAuditorId(long auditorId);

	/**
	 * Returns the auditor name of this budget application.
	 *
	 * @return the auditor name of this budget application
	 */
	@AutoEscape
	public String getAuditorName();

	/**
	 * Sets the auditor name of this budget application.
	 *
	 * @param auditorName the auditor name of this budget application
	 */
	public void setAuditorName(String auditorName);

	/**
	 * Returns the audit date of this budget application.
	 *
	 * @return the audit date of this budget application
	 */
	public Date getAuditDate();

	/**
	 * Sets the audit date of this budget application.
	 *
	 * @param auditDate the audit date of this budget application
	 */
	public void setAuditDate(Date auditDate);

	/**
	 * Returns the approver ID of this budget application.
	 *
	 * @return the approver ID of this budget application
	 */
	public long getApproverId();

	/**
	 * Sets the approver ID of this budget application.
	 *
	 * @param approverId the approver ID of this budget application
	 */
	public void setApproverId(long approverId);

	/**
	 * Returns the approver name of this budget application.
	 *
	 * @return the approver name of this budget application
	 */
	@AutoEscape
	public String getApproverName();

	/**
	 * Sets the approver name of this budget application.
	 *
	 * @param approverName the approver name of this budget application
	 */
	public void setApproverName(String approverName);

	/**
	 * Returns the approve date of this budget application.
	 *
	 * @return the approve date of this budget application
	 */
	public Date getApproveDate();

	/**
	 * Sets the approve date of this budget application.
	 *
	 * @param approveDate the approve date of this budget application
	 */
	public void setApproveDate(Date approveDate);

	/**
	 * Returns the finisher ID of this budget application.
	 *
	 * @return the finisher ID of this budget application
	 */
	public long getFinisherId();

	/**
	 * Sets the finisher ID of this budget application.
	 *
	 * @param finisherId the finisher ID of this budget application
	 */
	public void setFinisherId(long finisherId);

	/**
	 * Returns the finisher name of this budget application.
	 *
	 * @return the finisher name of this budget application
	 */
	@AutoEscape
	public String getFinisherName();

	/**
	 * Sets the finisher name of this budget application.
	 *
	 * @param finisherName the finisher name of this budget application
	 */
	public void setFinisherName(String finisherName);

	/**
	 * Returns the finisher date of this budget application.
	 *
	 * @return the finisher date of this budget application
	 */
	public Date getFinisherDate();

	/**
	 * Sets the finisher date of this budget application.
	 *
	 * @param finisherDate the finisher date of this budget application
	 */
	public void setFinisherDate(Date finisherDate);

	/**
	 * Returns the reject reason of this budget application.
	 *
	 * @return the reject reason of this budget application
	 */
	@AutoEscape
	public String getRejectReason();

	/**
	 * Sets the reject reason of this budget application.
	 *
	 * @param rejectReason the reject reason of this budget application
	 */
	public void setRejectReason(String rejectReason);

	/**
	 * Returns the application status of this budget application.
	 *
	 * @return the application status of this budget application
	 */
	@AutoEscape
	public String getApplicationStatus();

	/**
	 * Sets the application status of this budget application.
	 *
	 * @param applicationStatus the application status of this budget application
	 */
	public void setApplicationStatus(String applicationStatus);

	/**
	 * Returns the application description of this budget application.
	 *
	 * @return the application description of this budget application
	 */
	@AutoEscape
	public String getApplicationDescription();

	/**
	 * Sets the application description of this budget application.
	 *
	 * @param applicationDescription the application description of this budget application
	 */
	public void setApplicationDescription(String applicationDescription);

	/**
	 * Returns the application total of this budget application.
	 *
	 * @return the application total of this budget application
	 */
	public double getApplicationTotal();

	/**
	 * Sets the application total of this budget application.
	 *
	 * @param applicationTotal the application total of this budget application
	 */
	public void setApplicationTotal(double applicationTotal);

	/**
	 * Returns the project name of this budget application.
	 *
	 * @return the project name of this budget application
	 */
	@AutoEscape
	public String getProjectName();

	/**
	 * Sets the project name of this budget application.
	 *
	 * @param projectName the project name of this budget application
	 */
	public void setProjectName(String projectName);

	/**
	 * Returns the budget name of this budget application.
	 *
	 * @return the budget name of this budget application
	 */
	@AutoEscape
	public String getBudgetName();

	/**
	 * Sets the budget name of this budget application.
	 *
	 * @param budgetName the budget name of this budget application
	 */
	public void setBudgetName(String budgetName);

	/**
	 * Returns the budget item ID of this budget application.
	 *
	 * @return the budget item ID of this budget application
	 */
	public long getBudgetItemId();

	/**
	 * Sets the budget item ID of this budget application.
	 *
	 * @param budgetItemId the budget item ID of this budget application
	 */
	public void setBudgetItemId(long budgetItemId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.startarget.portlet.model.BudgetApplication budgetApplication);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.startarget.portlet.model.BudgetApplication> toCacheModel();

	@Override
	public com.startarget.portlet.model.BudgetApplication toEscapedModel();

	@Override
	public com.startarget.portlet.model.BudgetApplication toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}