/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.startarget.portlet.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Budget service. Represents a row in the &quot;lims_Budget&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.startarget.portlet.model.impl.BudgetModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.startarget.portlet.model.impl.BudgetImpl}.
 * </p>
 *
 * @author chaojie
 * @see Budget
 * @see com.startarget.portlet.model.impl.BudgetImpl
 * @see com.startarget.portlet.model.impl.BudgetModelImpl
 * @generated
 */
public interface BudgetModel extends BaseModel<Budget>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a budget model instance should use the {@link Budget} interface instead.
	 */

	/**
	 * Returns the primary key of this budget.
	 *
	 * @return the primary key of this budget
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this budget.
	 *
	 * @param primaryKey the primary key of this budget
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the budget ID of this budget.
	 *
	 * @return the budget ID of this budget
	 */
	public long getBudgetId();

	/**
	 * Sets the budget ID of this budget.
	 *
	 * @param budgetId the budget ID of this budget
	 */
	public void setBudgetId(long budgetId);

	/**
	 * Returns the group ID of this budget.
	 *
	 * @return the group ID of this budget
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this budget.
	 *
	 * @param groupId the group ID of this budget
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this budget.
	 *
	 * @return the company ID of this budget
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this budget.
	 *
	 * @param companyId the company ID of this budget
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this budget.
	 *
	 * @return the user ID of this budget
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this budget.
	 *
	 * @param userId the user ID of this budget
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this budget.
	 *
	 * @return the user uuid of this budget
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this budget.
	 *
	 * @param userUuid the user uuid of this budget
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this budget.
	 *
	 * @return the user name of this budget
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this budget.
	 *
	 * @param userName the user name of this budget
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this budget.
	 *
	 * @return the create date of this budget
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this budget.
	 *
	 * @param createDate the create date of this budget
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this budget.
	 *
	 * @return the modified date of this budget
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this budget.
	 *
	 * @param modifiedDate the modified date of this budget
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the project name of this budget.
	 *
	 * @return the project name of this budget
	 */
	@AutoEscape
	public String getProjectName();

	/**
	 * Sets the project name of this budget.
	 *
	 * @param projectName the project name of this budget
	 */
	public void setProjectName(String projectName);

	/**
	 * Returns the budget name of this budget.
	 *
	 * @return the budget name of this budget
	 */
	@AutoEscape
	public String getBudgetName();

	/**
	 * Sets the budget name of this budget.
	 *
	 * @param budgetName the budget name of this budget
	 */
	public void setBudgetName(String budgetName);

	/**
	 * Returns the budget start year of this budget.
	 *
	 * @return the budget start year of this budget
	 */
	public int getBudgetStartYear();

	/**
	 * Sets the budget start year of this budget.
	 *
	 * @param budgetStartYear the budget start year of this budget
	 */
	public void setBudgetStartYear(int budgetStartYear);

	/**
	 * Returns the budget end year of this budget.
	 *
	 * @return the budget end year of this budget
	 */
	public int getBudgetEndYear();

	/**
	 * Sets the budget end year of this budget.
	 *
	 * @param budgetEndYear the budget end year of this budget
	 */
	public void setBudgetEndYear(int budgetEndYear);

	/**
	 * Returns the budget total of this budget.
	 *
	 * @return the budget total of this budget
	 */
	public double getBudgetTotal();

	/**
	 * Sets the budget total of this budget.
	 *
	 * @param budgetTotal the budget total of this budget
	 */
	public void setBudgetTotal(double budgetTotal);

	/**
	 * Returns the budget arrival of this budget.
	 *
	 * @return the budget arrival of this budget
	 */
	public double getBudgetArrival();

	/**
	 * Sets the budget arrival of this budget.
	 *
	 * @param budgetArrival the budget arrival of this budget
	 */
	public void setBudgetArrival(double budgetArrival);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.startarget.portlet.model.Budget budget);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.startarget.portlet.model.Budget> toCacheModel();

	@Override
	public com.startarget.portlet.model.Budget toEscapedModel();

	@Override
	public com.startarget.portlet.model.Budget toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}